#!/usr/bin/env bash
# cofigure nginx server to have a custom 404 page

apt-get update
apt-get install -y nginx
ERROR="404.html"

echo "Ceci n'est pas une page" > $ERROR
mv $ERROR /var/www/html/
sed -i "s/#error_page/error_page/" /etc/nginx/sites-available/default
service nginx restart
service nginx reload
