#!/usr/bin/env bash
# cofigure nginx server to have a custom 404 page

apt-get update
apt-get install -y nginx
ERROR="404.html"
service nginx start
echo "Ceci n'est pas une page" > $ERROR
mv $ERROR /var/www/html/
error_pag="\\\terror_page 404 /404.html;\n\tlocation = /404.html {\n\t\troot /var/www/html;\n\t\tinternal;\n\t}"
sed -i "27i $error_pag" /etc/nginx/sites-available/default
service nginx restart
service nginx reload
