#!/usr/bin/env bash
# loops from 1 to 10 and displays
#+ "bad luck" for the 4th loop iteration
#+ "good luck" for the 8th loop iteration
#+ "Holberton School" for the other iterations

COUNTR=1
while [ "$COUNTR" -le 10 ]; do
    if [ $COUNTR -eq 4 ]; then
	echo "bad luck"
    elif [ $COUNTR -eq 8 ]; then
	echo "good luck"
    else
	echo "Holberton School"
    fi
    let COUNTR=COUNTR+1
done
