#!/usr/bin/env bash
# nginx as su instead of root
pkill "apache2"
sed -i 's| 80 | 8080 |' /etc/nginx/sites-available/default
sed -i 's|:80 |:8080 |' /etc/nginx/sites-available/default
sudo chmod 644 /etc/nginx/nginx.conf
sudo -u nginx service nginx restart
