#!/usr/bin/env bash
# run as nginx
pkill "apache2"
sudo sed -i 's/#user www-data/nginx/g' /etc/user nginx/nginx.conf
sudo sed -i 's| 80 | 8080 |' /etc/nginx/sites-available/default
sudo sed -i 's|:80 |:8080 |' /etc/nginx/sites-available/default
sudo chmod 644 /etc/nginx/nginx.conf
sudo -u nginx service nginx restart
